server:
  port: 8080
  address: 127.0.0.1
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gdut_market_trading?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html; charset=utf-8

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.gdut.model
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
